### ISSUE TITLE
Not returning errors

### ISSUE THREAD

**Issue by jaxgeller** [umdio/umdio#1]
Hey so far it's got great response times and working out great. However, i did find a little bug. Looking up courses that sections dont exist returns a 200 null. For example, 

`http://api.umd.io/v0/courses/ENES100` returns 200 with valid json
`http://api.umd.io/v0/courses/ENES101` returns 200 with null

When it should return 400 with an error code.

**Comment by jaxgeller** [comment]
just saw http://umd.io/#errors. Perhaps a not found message would be better, otherwise good work.

**Comment by dannyjlaurence** [comment]
Wouldn't it be a 404 not found?
