### ISSUE TITLE
200 status returned with a 404 error code

### ISSUE THREAD

**Issue by sw3dish** [umdio/umdio#10]
For the following 404 examples in the documentation, 
```
http://api.umd.io/v5/courses
http://api.umd.io/courses
http://api.umd.io/v0/course
http://api.umd.io/v0/courses/ENGL115
```
the status code returned is 200 OK. However, the JSON key `error_code` returns:
```
error_code : 404
```
Since for the example for a 400 error,
```
http://api.umd.io/v0/courses/ene10
```
returns a 400 status code along with the JSON key `error_code`
```
error_code : 400
```
should this be the same for 404 errors? i.e. a 404 status code being returned as well?

**Comment by nickaversano** [comment]
Thanks for catching this!
