### ISSUE TITLE
Unexpected in Courses endpoint

### ISSUE THREAD

**Issue by sw3dish** [umdio/umdio#11]
Sending a GET request to `http://api.umd.io/v0/courses` returns results that start in the Cs.
```
[  
   {  
      "course_id":"CPPL100",
      "name":"College Park Scholars: Public Leadership First-Year Colloquium I",
      "dept_id":"CPPL",
      "department":"College Park Scholars-Public Leadership",
      "semester":"201508",
      "credits":"1",
      ...
]


```
As default sort is ascending, I would expect it to start at A, as in the documentation.

Also, a GET request to `http://api.umd.io/v0/courses` with no params, according to the documentation, should return an Array of objects with three properties: `course_id`, `name`, and `department`. 
```
[
  {
    "course_id": "AASP100",
    "name": "Introduction to African American Studies",
    "department": "African American Studies"
  },
  {
    "course_id": "AASP101",
    "name": "Public Policy and the Black Community",
    "department":"African American Studies"
  }
]
```
Instead, an array of full Course objects are returned. Is this intended?

**Comment by nickaversano** [comment]
A GET request to /courses as of right now returns the courses in no particular order. Perhaps, as you mentioned, alphabetical by course_id would make more sense.
As to your second point, we do need to update our docs. /courses/list returns the array with three properties.

**Comment by rrcobb** [comment]
Docs are updated to reflect the difference between /courses and /courses/list, and the list returned is sorted alphanumerically by default.
