### ISSUE TITLE
New courses are not sorted properly

### ISSUE THREAD

**Issue by McIntireEvan** [umdio/umdio#123]
Courses such as CMSC389M appear at the end of results (https://api.umd.io/courses?dept_id=cmsc), rather than where they should in alphabetical order.

This is probably on account of them being added in later. A good fix would be adding a new view in `startup.sql` that sorts the courses, and then query from that.

**Comment by nyaculak** [comment]
I think a better alternative to creating a view might be to add an ORDER BY clause to the query. Maybe we should also add 2 url params (order by column and direction) to let users change the default sorting behavior.

**Comment by McIntireEvan** [comment]
I looked into it a bit more, and we do already have such url params, and there already is an ORDER BY clause in effect, and as it turns out, it orders by `id ASC` by default, which explains this behavior. So, changing the default (at least for the courses) can then fix this without needing a view.

**Comment by nyaculak** [comment]
Cool! I think we should consider API calls without an order_by param to have no guarantees on sorting, so this won't count as a breaking change.

**Comment by McIntireEvan** [comment]
resolved by #126
