### ISSUE TITLE
Search queries on sections endpoint return results not matching parameters

### ISSUE THREAD

**Issue by geekman7473** [umdio/umdio#131]
For example, [https://api.umd.io/v0/courses/sections?semester=201908&page=50&per_page=100](https://api.umd.io/v0/courses/sections?semester=201908&page=50&per_page=100) includes "BUSM708-0901" which is listed under "201708," not "201908"

**Comment by McIntireEvan** [comment]
I think this was solved in #122 but I might not have deployed since then. I'll try to have this resolved soon, either way
