### ISSUE TITLE
Consistently getting gateway timeouts for sections API

### ISSUE THREAD

**Issue by SphinxNumberNine** [umdio/umdio#132]
All requests to the sections API are timing out. Am I missing a header or something?

As an aside, I did some digging through the code and found that the "open seats" parameter is being saved, but never returned as part of the section object. Is this intended for some reason?

**Comment by kwam1na** [comment]
I’m getting the same error too trying to access anything from the API.

**Comment by McIntireEvan** [comment]
Hey, sorry for taking time to get back to you - I restarted the server and I'm not getting this issue. I'll look through the logs and see if anything comes up to explain this. If it happens again, please respond here again and I'll try and get to it quicker!

**Comment by SphinxNumberNine** [comment]
Still timing out on my end :(

**Comment by McIntireEvan** [comment]
Could you post the request you're doing?

**Comment by McIntireEvan** [comment]
Quick update: I'm getting the timeout too, now - I'll investigate and try to resolve tonight

**Comment by McIntireEvan** [comment]
Updated and restarted the server last night - we still seem to be up and running fine, I'll keep this issue open for a few days though in case issues resurface
