### ISSUE TITLE
`/courses/list` always returns courses for Fall 2019, ignoring the semester parameter

### ISSUE THREAD

**Issue by ZachThren** [umdio/umdio#151]
All of the following urls show course listings for the Fall 2019 schedule of classes:

https://api.umd.io/v0/courses/list?semester=201901
https://api.umd.io/v0/courses/list?semester=201905
https://api.umd.io/v0/courses/list?semester=201908
https://api.umd.io/v0/courses/list?semester=201912
https://api.umd.io/v0/courses/list?semester=202001

**Comment by McIntireEvan** [comment]
Thanks for the bug report! I can indeed confirm this, and plan to have a fix released in the next ~36 hours

**Comment by McIntireEvan** [comment]
Pushing a fix now. Issue was two things
- `find_courses_in_sem` function had a hardcoded semester (probably for debugging, never got changed back)
- the calling function passed `params[:semester]` rather than `params['semester']
