### ISSUE TITLE
For the get  section  request, does the open seat value get updated?

### ISSUE THREAD

**Issue by VIctorUduma** [umdio/umdio#158]
for the get section request that gives back a section object, does the open seat value in the object get updated as seats are being filled up? if so, how frequent does it  update? . greatly appreciated.
is there a way to get an update on how many seats are in a class?

**Comment by McIntireEvan** [comment]
Apologies for the delayed response!

Currently, it is updated very infrequently. With the launch of v1, which should be coming soon, I'll try and have it updated every day or so

**Comment by VIctorUduma** [comment]
thank you for the response!

**Comment by McIntireEvan** [comment]
No problem! I also just updated the sections manually, so the open_seat count should be up to date as of this message.

**Comment by VIctorUduma** [comment]
thank you!  also congrats on the soon release of version 1!
