### ISSUE TITLE
add spring 2021 (semester 202101) course data

### ISSUE THREAD

**Issue by tybug** [umdio/umdio#168]
testudo's had spring 2021 courses for a while now. I'm happy to run the scraper myself and provide a database dump for the 202101 courses if that makes your life easier, just tell me where to pr / send it.

**Comment by McIntireEvan** [comment]
Hi @tybug!

Apologies, I graduated and don't actively maintain this anymore. I'll run the scraper, and see if I can get a cron job going to keep it active. I thought we had one, but looks like not.

**Comment by McIntireEvan** [comment]
Hi, it should be updated now. Let me know if you have any issues.

**Comment by tybug** [comment]
works as expected, thanks!
