### ISSUE TITLE
add Fall 2021 (semester 202108) course data

### ISSUE THREAD

**Issue by tybug** [umdio/umdio#171]
similar to #168.

If you don't want to actively maintain this anymore, would you be willing to add me as maintainer in some capacity so I can run the scripts myself when appropriate? Would be happy to take over as a maintainer of umd.io in full as well if you're looking for someone to do so.

**Comment by McIntireEvan** [comment]
Hey @tybug - I graduated last year and haven't been actively maintaining things. Happy to chat and get you in a spot to run things

**Comment by tybug** [comment]
awesome - I'm tybug#8490 on discord, or let me know another medium of communication if you prefer

**Comment by McIntireEvan** [comment]
Discord is fine! I'll reach out later today. In the meantine, I just ran the scraper, so hopefully things should be up-to-date in a little bit.

**Comment by tybug** [comment]
just bumping this to say I haven't gotten a friend req yet, no rush though obviously if you haven't gotten around to it

**Comment by DonIsaac** [comment]
Any updates on this?

**Comment by tybug** [comment]
as an update: @McIntireEvan got back to me today and started the process of adding me as a maintainer, so I have access to the server and repos now and should be able to maintain things going forward

**Comment by DonIsaac** [comment]
@tybug @McIntireEvan Any chance I could also become a maintainer or otherwise so that I can help?

**Comment by McIntireEvan** [comment]
@DonIsaac , sure adding you as a contributor in the org. Happy to see interest in this project again :)

**Comment by DonIsaac** [comment]
@McIntireEvan thanks!

**Comment by tybug** [comment]
going to close this as resolved
