### ISSUE TITLE
`gen_ed` is wrong for `CCJS225`

### ISSUE THREAD

**Issue by tybug** [umdio/umdio#180]
https://api.umd.io/v1/courses/CCJS225

```json
"gen_ed": [
  [
    "DSHSDSSP",
    "SCIS"
  ]
],
```

should be
```json
"gen_ed": [
  [
    "DSHS",
    "SCIS",
  ],
  [
    "DSSP",
    "SCIS"
  ]
],
```

similarly for any course that allows you to choose between geneds, such as `HIST187`, `HIST200`, etc (scroll down https://app.testudo.umd.edu/soc/gen-ed/202108/DSHS to find a bunch).

**Comment by cheymonty** [comment]
I think I can work on this over the weekend

**Comment by DonIsaac** [comment]
@cheymonty thank you!

**Comment by tybug** [comment]
I actually already have a fix for this here: https://github.com/umdio/umdio/tree/fix-gened-scrape. I need to touch up a few things which is why I haven't PRd it but I should be able to do so by tomorrow
