### ISSUE TITLE
GET /v1/majors/list returns an empty array

### ISSUE THREAD

**Issue by DonIsaac** [umdio/umdio#192]
[GET /v1/majors/list](https://api.umd.io/v1/majors/list) returns an empty array. #173 might have fixed this. If so, then the server needs to be updated with these changes, followed by re-running `scrape`. If not we need to pin this down. This is a pretty bad bug and should be addressed ASAP.

**Comment by McIntireEvan** [comment]
Technically fixed, but seems to have some issues with the `major_id` (which is just the `pid` from the database), and some extra spacing in names

```
{"major_id":118,"name":"Accounting ","college":"  Robert H. Smith School of Business","url":"https://www.rhsmith.umd.edu/programs/undergraduate/academics/academic-majors"}
```

**Comment by DonIsaac** [comment]
Looks like we'll need to run `.trim()`

**Comment by DonIsaac** [comment]
so i figured out that `strip` isn't working because the "white space" isn't actually whitespace - it's a combination of character codes `192` and `160`, which are some weird extended ASCII symbolds. Not sure how to remove these
