### ISSUE TITLE
Use proxy for bus requests

### ISSUE THREAD

**Issue by jaxgeller** [umdio/umdio#2]
Yo! Umd.io is looking sweet, saw that you guys are working on the Bus API and it looks pretty cool. One thing I noticed with a43102b5e733ff3a12c10112c94b4d72d6b1f3d9 is that there's another request on top of the request to umd.io, i think for speed you should add nginx as a reverse proxy to the bus API. For example, i set up this server on DO.

http://45.55.130.81/bus/?a=umd&command=routeList

You could add you domain name, and basically forward any request from http://umd.io/bus --> http://webservices.nextbus.com/. 

Here's the nginx config i used, it's really simple and effective.

```
location /bus/ {
    proxy_pass http://webservices.nextbus.com/service/publicJSONFeed;
}
```

Otherwise, things look awesome, keep up the good work.

**Comment by nickaversano** [comment]
Hey Jackson! Great idea!
One of the other things we wanted to do in addition to just sending back bus data from nextbus was to clean up their JSON objects a little bit to make them easier to work with. Could a reverse proxy still work in this case, can we grab the response from the proxy just before its sent to the client and alter it?

**Comment by jaxgeller** [comment]
Looks like it is possible, but you're going to have to dive deep into extending nginx with lua. I found this article that details that http://tech.3scale.net/2013/01/09/augment-your-api-without-touching-it/ . So maybe put this issue on the back-burner if cleaning up the json is important.

**Comment by rrcobb** [comment]
Caching should help with requests that aren't looking for to-the-minute location info - extending nginx probably won't be the priority for a while.

**Comment by jaxgeller** [comment]
Cool, well I'll close the issue and the server for now, but I thought I'd bring it to your attention.

**Comment by nickaversano** [comment]
I didn't know that this was possible.... thanks for the tip!

**Comment by jaxgeller** [comment]
It's great if you need to get around CORs problems for client-side apps https://gist.github.com/jaxgeller/4a0a66919b14f3a8f2ec
