### ISSUE TITLE
Issues when installing via Vagrant

### ISSUE THREAD

**Issue by sw3dish** [umdio/umdio#20]
[Here](http://pastebin.com/7kE57eiS)'s a paste of the output from attempting `vagrant up`.

`bundle exec rake up` still works and I can access the API through `localhost:3000`. However, navigating any endpoint doesn't return the expected data.

**Comment by nickaversano** [comment]
`rake up` runs a jekyll site which is separate from the api server. You don't have to use vagrant to run the website, though it supposedly made things easier to set up... you're pastebin is private, maybe @rrcobb knows what's wrong?

**Comment by sw3dish** [comment]
[Here](http://pastebin.com/7kE57eiS) is an updated link. @rrcobb and I looked at it last night. The output seems to point to an error in the course scraper, which caused the rest of the scrapers, namely the ones corresponding to the bus and map endpoints, to fail also.
