### ISSUE TITLE
Data Entry - Scraping University Resources vs Making Custom Frontend

### ISSUE THREAD

**Issue by hydrosquall** [umdio/umdio#21]
You guys are doing a great job with the api!

Looked through the ideas doc- curious about your thoughts on continuing to serve data by scraping university resources, vs building a frontend for keeping track of the new data types you're proposing (assuming they're not already available on the web to be scraped).

This is something I'm working on up north as well- currently just using google spreadsheets as the site of data entry. I just think you guys are laying down a really good boilerplate on rails and am curious whether you've seen any good data entry frontends for university data applications.

**Comment by nickaversano** [comment]
Thanks! Not sure what you mean by "building a frontend for keeping track of the new data types"... Do  you mean a website where students can submit their own data? Or an API that allows POSTing to as well as just GETting data. We're actually using Sinatra, not Rails.

Data entry sounds like a pain. Wherever possible, automating the process (via scraping or whatever) seems like the way to go.

**Comment by hydrosquall** [comment]
Ah, I could have worded that more clearly. I was describing a site for some admin team to submit/edit the existing data, assuming the data isn't already being posted on the web already. If it's up on the web already, then scraping definitely seems like the convenient way to go!

Making a dedicate data entry endpoint would guard against the API breaking due to the website being redesigned and having page structure (class names, IDs, etc) changed.

**Comment by nickaversano** [comment]
We use api versioning which is pretty resistant to breaking other people's stuff. Closing this
