### ISSUE TITLE
GET /v1/bus/routes/:route_id/arrivals/:stop_id is broken

### ISSUE THREAD

**Issue by DonIsaac** [umdio/umdio#223]
# Description

Discovered in #222, see changes for more details.

Calling `GET /v1/bus/routes/:route_id/arrivals/:stop_id` with valid/existing route id and stop id returns `Bus Service Unavailable`. Oddly enough, the v0 version of this route works just fine.

EDIT: Problem is caused by `app/helpers/request.rb#wrapRequest_v1`.
**Expected Behavior**

Route returns a valid route arrival payload.

**Actual Behavior**

Returns `Bus Service Unavailable`

# Reproduction and Context

Example routes:
- https://api.umd.io/v1/bus/routes/104/arrivals/regdrgar_d
- https://api.umd.io/v1/bus/routes/104/arrivals/paingree
- https://api.umd.io/v1/bus/routes/108/arrivals/artsoci

**Comment by Josiassejod1** [comment]
Can I claim this @DonIsaac ?

**Comment by Josiassejod1** [comment]
have a pr I need access

**Comment by DonIsaac** [comment]
> have a pr I need access

You can create a fork of the repo and create a PR that way

**Comment by Josiassejod1** [comment]
dumb question but how do I hit the endpoint locally? its not localhost:8081 right? @DonIsaac

**Comment by Josiassejod1** [comment]
Got a pr here https://github.com/umdio/umdio/pull/224

**Comment by tybug** [comment]
@Josiassejod1 you want port 3000, eg http://0.0.0.0:3000/v1/bus/locations

**Comment by tybug** [comment]
closed by https://github.com/umdio/umdio/pull/224
