### ISSUE TITLE
nextbus has moved

### ISSUE THREAD

**Issue by tybug** [umdio/umdio#228]
now located at https://retro.umoiq.com/. We'll need to update our endpoints to use this domain. Hopefully that's the only adjustment necessary? Though I worry because https://retro.umoiq.com/service/publicJSONFeed?a=umd&command=schedule doesn't seem to return all routes anymore...

docs: https://retro.umoiq.com/xmlFeedDocs/NextBusXMLFeed.pdf

**Comment by DonIsaac** [comment]
I won't be able to address this quickly. Can you get this one?

**Comment by tybug** [comment]
don't think so, it's my last week of work and then I'm on vacation for two weeks after that
