### ISSUE TITLE
Outdated Data

### ISSUE THREAD

**Issue by colinking** [umdio/umdio#23]
The course data doesn't yet include fall 2016's schedule of classes. (Querying `http://api.umd.io/v0/courses?semester>201601` returns an empty array)

Also: would it be possible to set up the course scrapers to run on a daily (or more frequently) basis? It would be useful to have live data on open seats and the waitlist for each class.

**Comment by nickaversano** [comment]
Just updated the courses now! As of right now, we just manually run the courses scraper but I agree automating this would be sweet! We actually do have a courses scraper that runs every 30 minutes but it looks like it was pulling from an old semester. Again automating this to know the current semester would be nice as well.

**Comment by domthebigbomb** [comment]
Couldnt you just calculate the semester based on the current date?

**Comment by nickaversano** [comment]
We could, however we weren't sure if the university schedule for releasing courses are consistent enough. One possible workaround is looking at the term from this page: https://ntst.umd.edu/soc/

**Comment by nickaversano** [comment]
grab the current semester from testudo save in a local file / cache in memory and only update once a day in a cron job or something. also might be worth doing cron jobs through a gem rather than just on the server

**Comment by nickaversano** [comment]
Thanks to @rstumbaugh this should be fixed! Just need to setup a cron job to run every once and a while
