### ISSUE TITLE
Data Not in Sync with Testudo?

### ISSUE THREAD

**Issue by DylanSpeiser** [umdio/umdio#231]
Getting seat data by course and section is not in sync with Testudo. I checked for courses HNUH288A, PHYS260, and PHYS298B, and they were all out of sync with Testudo.
Is there a delay for the API to update? How often does it do that?

**Comment by tybug** [comment]
this is a longstanding issue which I thought I had squashed recently. Ideally it would update once a day. I'll take another look soon.

**Comment by tybug** [comment]
This should be fixed now. We now pull from testudo daily at 1 am. Please report if you see that umdio is greater than a day out of sync with testudo!
