### ISSUE TITLE
api sections call

### ISSUE THREAD

**Issue by jsondevers** [umdio/umdio#242]
# Description
When trying to call the API for sections given the parameters, the returning json does not specify the correct course. 

```python
def sections(course=None, section_id=None, semester=None, section_number=None):
    params = {
        "course": course,
        "section_id": section_id,
        "semester": semester,
        "section_number": section_number,
    }
    url = BASE_URL + "courses/sections?" + urlencode(params)
    response = requests.get(url)
    sections = response.json()
    return sections


example = sections(course="ENGL101", section_id="ENGL101-0101", semester=202201)
print(example[0])
```
produces:
```bash
{'course': 'AASP100', 'section_id': 'AASP100-0101', 'semester': '202201', 'number': '0101', 'seats': '35', 'meetings': [{'days': 'MWF', 'room': '1119', 'building': 'SQH', 'classtype': '', 'start_time': '10:00am', 'end_time': '10:50am'}], 'open_seats': '0', 'waitlist': '0', 'instructors': ['Shane Walsh']}
```
when it should be giving english sections, no?

this is using the base url
```python
BASE_URL = "https://api.umd.io/v1/"
```

**Comment by tybug** [comment]
You are hitting the `https://api.umd.io/v1/courses/sections` endpoint, which returns all sections (in alphabetical order, hence starting with AASP100). To retrieve a specific section, use `https://api.umd.io/v1/courses/sections/{section_id}`, eg https://api.umd.io/v1/courses/sections/ENGL101-0101.

**Comment by tybug** [comment]
If you want to get a list of sections filtered by course, you should be using `course_id`, not `course` as in your code.

**Comment by jsondevers** [comment]
is there not a way to alternate the API URL to specify a semester?

**Comment by tybug** [comment]
I don't quite understand your goal - both the [`/sections/{section_id}`](https://beta.umd.io/#operation/getSectionsByIds) and [`/sections`](https://beta.umd.io/#operation/getSections) endpoint have a `semester` parameter which you can use to specify a semester. Is that not sufficient for your use case?

**Comment by jsondevers** [comment]
for example if i did 
```python
url = "https://api.umd.io/v1/courses/sections/ENGL101-0101"
response = requests.get(url)
course = response.json()
return course
``` 
produces
``` bash 
[{'course': 'ENGL101', 'section_id': 'ENGL101-0101', 'semester': '202301', 'number': '0101', 'seats': '17', 'meetings': [{'days': 'MWF', 'room': '0221', 'building': 'TWS', 'classtype': '', 'start_time': '9:00am', 'end_time': '9:50am'}], 'open_seats': '7', 'waitlist': '0', 'instructors': ['Brianne Friel']}]
```
this specifies the semester for me? what if i was looking to have a semester id of a previous year?

**Comment by tybug** [comment]
When you don't specify a semester, it uses the current semester. Use the `semester` parameter if you want to specify a semester, as above: `https://api.umd.io/v1/courses/sections/ENGL101-0101?semester={semester_id}` ([example](https://api.umd.io/v1/courses/sections/ENGL101-0101?semester=202201)).

**Comment by jsondevers** [comment]
thank you, this answers my question
