### ISSUE TITLE
Malformed JSON response to buildings list query

### ISSUE THREAD

**Issue by adrusi** [umdio/umdio#3]
When i query the buildings list, javascript's standard `JSON.parse` fails due to an unexpected comma, with the error:

```
undefined:1
88","lat":"38.9902169"},{"name":"J.H. Kehoe Track and Ludwig Field",,"code":""
                                                                    ^
SyntaxError: Unexpected token ,
  at Object.parse (native)
  at IncomingMessage.<anonymous> (/home/adrusi/Code/umdio/index.coffee:19:24)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by rrcobb** [comment]
I'm having trouble reproducing this. http://api.umd.io/v0/map/buildings is returning http://pastebin.com/cREEapUf for me, which has no extra comma. Any more context to the url that's giving you the error?

**Comment by rrcobb** [comment]
Figured out that the javascript join() joins with a comma by default. Not an api issue!
