### ISSUE TITLE
Jekyll serve not running

### ISSUE THREAD

**Issue by nickaversano** [umdio/umdio#30]
From @rstumbaugh:
I still can't seem to get jekyll running on my machine. I'm running jekyll serve from the docs/ folder, but it looks like the _config.yml is in the src/ folder. Even when I put the config file in the docs/ folder, jekyll can't find any of the posts and the Sass doesn't get compiled. Any ideas?

**Comment by nickaversano** [comment]
@rstumbaugh can you post an error message, platform and more relevant details?

**Comment by rstumbaugh** [comment]
I'm running everything on Vagrant, and my branch is up to date with this repo's master. The first message I see when I run `jekyll serve` is `Configuration file: none`. I also get a bunch of errors saying  `Build Warning: Layout 'post' requested in src/courses/_posts/2015-02-27-search-courses.md does not exist.` I get the same error for pretty much every other markdown file. 

I also get errors saying `** ERROR: directory is already being watched! **` for `docs/static/images`, `docs/static/js`, `docs/src/_sass/normalize, docs/static/assets/stylesheets`, `docs/bower_components/bourbon/app/assets/stylesheets`, and `docs/bower_components/neat/app/assets/stylesheets`. 

Eventually, I do get the message `Server address: http://127.0.0.1:4000/` and `Server running... press ctrl-c to stop.` Safari tells me "the server unexpectedly dropped the connection" when I try to visit localhost:4000.

**Comment by nickaversano** [comment]
hmm... try running it outside of vagrant. I don't think we ever set that up properly to run jekyll from

**Comment by rstumbaugh** [comment]
Looks like the same type of errors when running locally. At least Safari can open the page, but it looks like it can't open any of the markdown files, and the Sass isn't being compiled. When I run `jekyll serve` in the `src` folder where the config file is, I get a "No such file" error for `docs/src/css/main.css`. [Here are some pics](http://imgur.com/a/L0Nvd) of my error messages if it helps at all.

**Comment by nickaversano** [comment]
Yeah it's not very clear, but apparently we're doing something non standard (and I forget why). The command to run the docs is Makefile. To serve them try running `jekyll serve -s src/ -d public/` from the `docs` folder

**Comment by rstumbaugh** [comment]
Yep, that works great. All good now.
