### ISSUE TITLE
Special Gen Ed cases

### ISSUE THREAD

**Issue by rstumbaugh** [umdio/umdio#33]
Looks like the current method of parsing the Gen Eds for a course just check for Gen Ed codes separated by commas. When a course's gen ed requirements look like "DSNS or DSSP", this causes the gen ed to be parsed as "DSNSDSSP". I would start working on a fix, but I'm not exactly sure how the "or" case should be handled. Just adding it to the Gen Ed array wouldn't be very clear (is it DSNS, but I think adding "ABCD or WXYZ" means the course wouldn't appear in the search results if you were searching something like `/courses?gen_ed=ABCD`. There are even weirder situations like "DSNL (if taken with WXYZ123) or DSNS in the case of [AOSC200](https://ntst.umd.edu/soc/201608/AOSC/AOSC200). Maybe just split by commas, store everything in an array, and do a text search instead of the standard mongoDB search?

**Comment by nickaversano** [comment]
Good catch. Probably split by commas and whitespace or something. Unclear what to do with the conditionals though. E.g. from your example: `DSNL (if taken with AOSC201)`

**Comment by rstumbaugh** [comment]
Maybe something like 2 fields associated with Gen Eds? One field that will just store the Gen Ed codes found while scraping and another field that will store the literal text from the site? First can be used for searching, and the second can be used for the results (using the prev example):
`gen_ed: [DSNL (if take with AOSC201) or DSNS]`
`gen_ed_codes: [DSNL, DSNS]`

The URL can stay the same (`/courses?gen_ed=DSNL`) but when searching / returning the info just translate `gen_ed` argument to `gen_ed_codes`. To the user it looks like they searched for `gen_ed=...`, but mongoDB actually does a search for `gen_ed_codes=...`. `gen_ed_codes` is hidden from the user and just used for searching. Might be a little hackish though

**Comment by rstumbaugh** [comment]
Actually it looks like that's way more complex than it needs to be. Searching by regex in MongoDB will search array items too, so something like `find({ gen_ed: { $regex: "DSHS" }})` will work for these special cases. It looks like fixing the scraping by just splitting by commas and storing the whole expression + adding a case to `params_search_query` will do the trick. Thoughts on this?

**Comment by nickaversano** [comment]
Regex would probably be slower than an array look up, but maybe not slow enough for it to matter
