### ISSUE TITLE
errors at api.umd.io/v0/bus/routes

### ISSUE THREAD

**Issue by Vermanator** [umdio/umdio#35]
in http://api.umd.io/v0/bus/routes, every bus route has a double entry **EXCEPT**:

- 125 Campus Circulator
- 129 Franklin Park at Greenbelt Station
- 130 Greenbelt
- 137 IKEA
- 138 Greenbelt
- 139 NASA Goddard
- 140 UMB Law
- 140 UMB Law
- 141 Gaithersburg Park & Ride
- 141 Gaithersburg Park & Ride

All other entries need to have an instance of it itself removed. 
Also many bus routes are deprecated but still show up such as the:

- 125 Campus Circulator
- 139 NASA Goddard
- 138 Greenbelt (is now the 143 Greenbelt)

**Comment by sdrozzy** [comment]
Looking into this.

**Comment by McIntireEvan** [comment]
I'm currently taking a look at this. My guess is that the scraper was run more than once, so it got polluted with duplicate entries.

I'm rewriting all the bus scrapers to be more modular/testable and prevent situations like this from happening more - I'll have more details soon

**Comment by McIntireEvan** [comment]
As an update; I reworte the bus route scraper here: https://github.com/McIntireEvan/umdio/blob/50cdd42bf131712c84cb04e651ce7b92c99aea31/app/scrapers/bus_routes_scraper.rb

I included command-line arguments so rescraping is easier

However, I'm using a newer version of the Mongo library, so it's not compatible with the rest of the code until we update that

**Comment by McIntireEvan** [comment]
I cleared the db, and re-ran the scraper. No more duplicates! I'll close this issue and open a follow-up one to look into the bus scraper and if it checks for dupes
