### ISSUE TITLE
Add Winter 2017 and Spring 2018 Semesters to umd.io database

### ISSUE THREAD

**Issue by nyaculak** [umdio/umdio#36]
Both semesters are available on the schedule of classes.

**Comment by sdrozzy** [comment]
@nyaculak the courses are up to date as of the current semester (Fall 2017). Right now the scrapper only runs up to the current semester even though the following 2 semesters are already available. It should probably check SOC (https://ntst.umd.edu/soc/) to see what semesters are available and pull all of them. Feel free to make that change :)

**Comment by nyaculak** [comment]
@sdrozzy Could you assign me to the issue? I have a fix ready, going to put up a PR soon.

**Comment by sdrozzy** [comment]
#39

**Comment by sdrozzy** [comment]
#39 Thanks @nyaculak! Next thing to do is run the scrapper on the server. I'll take care of that and then close the issue.

**Comment by sdrozzy** [comment]
Done
