### ISSUE TITLE
Unable to run docs server locally

### ISSUE THREAD

**Issue by nyaculak** [umdio/umdio#41]
I've tried to run the docs server locally, but there seems to be a problem with the configuration with regards to the styles. Executing the make file results in:
`	
jekyll build -s src/ -d public/
Configuration file: src/_config.yml
            Source: src/
       Destination: public/
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.6.0 | Error:  No such file or directory @ rb_sysopen - /home/nick/dev/web/umdio/docs/src/css/main.scss
`

**Comment by nyaculak** [comment]
Also, @sdrozzy has encountered the same issue

**Comment by McIntireEvan** [comment]
@nyaculak Is this fixed, now that we have docker?
