### ISSUE TITLE
Professors API doesn't sort by department?

### ISSUE THREAD

**Issue by fishnal** [umdio/umdio#43]
`http://api.umd.io/v0/professors?department=CMSC,BMGT&sort=-name` returns an empty array, `[]` instead of the list of professors in the CMSC and BMGT department (sorted by name) (note that this is the example provided on the website).

With some further testing, here's a table with some examples of the parameters that do and do not work for the professors API:

| Call                                                                      | Works? |
|---------------------------------------------------------------------------|--------|
| http://api.umd.io/v0/professors?department=CMSC                           | FALSE  |
| http://api.umd.io/v0/professors?semester=201801                           | TRUE   |
| http://api.umd.io/v0/professors?sort=name                                 | TRUE   |
| http://api.umd.io/v0/professors?semester=201801&sort=name                 | TRUE   |
| http://api.umd.io/v0/professors?department=CMSC&sort=name                 | FALSE  |
| http://api.umd.io/v0/professors?department=CMSC&semester=201801           | FALSE  |
| http://api.umd.io/v0/professors?semester=201801&department=CMSC&sort=name | FALSE  |

The `Call` column represents the GET HTTP request made, and the `Works` column indicates whether or not the call returned _anything_

It appears that filtering out professors by which department doesn't work as intended.

**Comment by sdrozzy** [comment]
@fishnal sorry for the delay. Played around with this and looks like you can need to use `departments` instead of `department`. Example: http://api.umd.io/v0/professors?departments=ENGL. The docs have a bit more info about this http://umd.io/professors/.

**Comment by fishnal** [comment]
Thanks for the clarification
