### ISSUE TITLE
Classes API is not updated with remaining open seats and waitlist numbers

### ISSUE THREAD

**Issue by dhruvnm** [umdio/umdio#44]
All of the classes in the class API show that all seats are open and that there are 0 students on the waitlist. If the API is scraping results live off testudo, it should probably update these numbers.

**Comment by dhruvnm** [comment]
After further experimenting it seems that the API does not scrape testudo for the most recent updates. For example, looking up CMSC411 with the API will yield only one section but on testudo there are two sections.

**Comment by sdrozzy** [comment]
@dhruvnm I'm running the scraper now (give it ~30 mins to update) and that should fix the incorrect sections issue. However, for live data, you should not rely on the API. Right now the scraper has to be run manually, but the plan is to get the scraper to run periodically in the future.
