### ISSUE TITLE
Inaccurate and conflicting documentation for courses

### ISSUE THREAD

**Issue by wkunkel** [umdio/umdio#5]
On the main page of your website, under "Sample requests and responses", you have:
> http://api\.umd.io/v0/courses/ENGL115
> 200: Returns empty braces, because ENGL115 is not a real course. If your app thinks it’ll get a real response here, it might break.

Which conflict with the documentation under "Courses", which says:
> Returns: The course object specified, or null

Which also conflicts with the actual response returned by "http://api.umd.io/v0/courses/ENGL115", which is:
> {"error_code":404,"message":"Course with course_id ENGL115 not found!","available_courses":"http://api\.umd.io/v0/courses","docs":"http://umd\.io/courses/"}

**Comment by rrcobb** [comment]
I'll update the docs to reflect what's actually happening. 

Does a 404 with a helpful message make the most sense here, or would an empty brace be more helpful?

**Comment by rrcobb** [comment]
Docs are now in line with reality - 404 error when the course isn't in the database
