### ISSUE TITLE
Multiple courses picked up as one

### ISSUE THREAD

**Issue by busterroni** [umdio/umdio#50]
On this page: http://api.umd.io/v0/courses?page=91

There is a `course_id`: "GVPT388WGVPT389GVPT390GVPT396GVPT397GVPT409CGVPT409EGVPT409HGVPT409IGVPT409OGVPT421GVPT423HGVPT429EGVPT432GVPT439AGVPT454GVPT456GVPT459EGVPT459MGVPT459OGVPT459RGVPT473GVPT479DGVPT479LGVPT479PGVPT479YGVPT482HGVPT722GVPT729MGVPT743GVPT771GVPT799GVPT808BGVPT808CGVPT831GVPT873GVPT888BGVPT888EGVPT898GVPT899"

It appears that the rest of the fields are just a concatenation of the information for all of those courses.

**Comment by busterroni** [comment]
This is now visible via this URL: https://api.umd.io/v0/courses?page=92&semester=201801

I guess new courses were added.

It's also a problem here, with two "courses": https://api.umd.io/v0/courses?semester=201808&page=48

    EDCP632EDCP640EDCP641EDCP652EDCP671EDCP682EDCP685EDCP697EDCP738EDCP741EDCP746EDCP772EDCP775EDCP789EDCP789QEDCP789REDCP789ZEDCP798EDCP798AEDCP799EDCP799AEDCP870EDCP888EDCP888AEDCP888CEDCP888GEDCP889EDCP889IEDCP898EDCP899
  
  EDCP738EDCP741EDCP746EDCP772EDCP775EDCP789EDCP789QEDCP789REDCP789ZEDCP798EDCP798AEDCP799EDCP799AEDCP870EDCP888EDCP888AEDCP888CEDCP888GEDCP889EDCP889IEDCP898EDCP899

Is there something in common between these three that might cause this to happen?

**Comment by McIntireEvan** [comment]
I don't clearly see anything in common with the courses, but I can confirm this isn't just on the live server, I checked my local version and it had the same issues, in the same spot. I think it's worth noting, the first course in one of those (EDCP632) isn't offered.

I think the first steps here are
1) See if this happens for previous semesters.
2) Run the scraper for just this semester on just that major, see if the issue still arises and if so, try and use logging to track it down.

I might have time to tackle this sometime soon, but if not those are my thoughts. This is definately something we should try to get fixed

**Comment by busterroni** [comment]
EDCP632 is offered in Fall 2018. That's also the semester the error occurs.

I haven't taken a look at how the scraper works but I might soon. If I do I'll try to track down the problem.

**Comment by McIntireEvan** [comment]
Whoops, testudo was showing me the spring. Perhaps it has something to do with the links in the course description?

**Comment by busterroni** [comment]
It's possible, but there are other courses with links in the course description that don't have this problem.

**Comment by McIntireEvan** [comment]
Well, I found the error. It's not actually on our end - if you inspect the html of the testudo page, you can see that the HTML is malformed in such a way that all the other course divs are children of the one that gets messed up

![image](https://user-images.githubusercontent.com/2966094/37993482-cbf33838-31dc-11e8-8d4c-056d78024be7.png)

**Comment by busterroni** [comment]
Interesting. And it looks like it happens twice on that page -- with EDCP738 as well. I'm looking and don't see anything unique to these courses that might make this happen.

For some reason, despite this bug occurring on umd.io with GVPT388 this semester, GVPT388 doesn't seem to have the same problem as the EDCP courses on Testudo (the `div` closes as expected). Is it possible that it was fixed on Testudo and umd.io hasn't retrieved the data since then?

**Comment by McIntireEvan** [comment]
It's very possible. I'll go in and rescrape 2018 soon, and hopefully that clears that up.

I think we can also adjust the css selectors that the scraper uses to avoid this by ignoring any child .course divs

**Comment by McIntireEvan** [comment]
Closing; TL;DR was it was an issue in the HTML, and is (probably) gone now. Improved scraper and DB control is coming soon, so anomalies like this can be easily addressed.
