### ISSUE TITLE
Gened error

### ISSUE THREAD

**Issue by busterroni** [umdio/umdio#59]
AOSC200's geneds are: DSNL (if taken with AOSC201) or DSNS, SCIS

I think umd.io has problems scraping that. This is what the API says the geneds for that course are: `["DSNL(fkwhAOSC201)DSNS","SCIS"]`

https://api.umd.io/v0/courses?semester=201808&page=6

**Comment by busterroni** [comment]
It appears that every course that has the error has an "or" in the geneds. It seems to just remove the "or" if a gened is "A or B". Here's a list of courses with this problem (it may not contain every course with the problem):

`AOSC200: DSNL(fkwhAOSC201)DSNS
AREC200: DSNSDSSP
ARHU275: DSHUDSSP
ARHU319: DSHUDSSP
BSCI160: DSNL(fkwhBSCI161)DSNS
BSCI170: DSNL(fkwhBSCI171)DSNS
BSCI189I: DSNLDSSP
BSOS289I: DSHSDSSP
BSST240: DSNL(fkwhBSST241)DSNS
CCJS225: DSHSDSSP
CHEM131: DSNL(fkwhCHM132)
CHEM131S: DSNL(fkwhCHM132)
ENGL275: DSHUDSSP
ENGL293: DSHUDSSP
ENGL294: DSHUDSSP
FMSC302: DSHSDSSP
GEOG130: DSHSDSSP
GEOG201: DSNL(fkwhO211)
GEOL100: DSNL(fkwhOL110)DSNS
GEOL120: DSNL(fkwhOL110)DSNS
HESP120: DSHSDSSP
HIST200: DSHSDSHU
HIST201: DSHSDSHU
HIST205: DSHSDSHU
HIST287: DSHSDSHU
HONR218C: DSHSDSHU
HONR268N: DSNSDSSP
JOUR150: DSHSDSSP
JWST233: DSHSDSHU
JWST326: DSHSDSSP
LARC160: DSHUDSSP
LASC234: DSHSDSHU
LASC234H: DSHSDSHU
PHIL209A: DSHUDSSP
PHIL209N: DSHSDSHU
PHYS102: DSNL(fkwhPHYS103)
PHYS199M: DSHSDSNS
PHYS260: DSNL(fkwhPHYS261)
PHYS260H: DSNL(fkwhPHYS261)
PHYS270: DSNL(fkwhPHYS271)
PHYS272: DSNL(fkwhPHYS275)
PHYS272H: DSNL(fkwhPHYS275)
PLCY201: DSHSDSSP
PSYC100: DSHSDSNS
PSYC221: DSHSDSSP
PSYC221H: DSHSDSSP
SPAN234: DSHSDSHU
SPAN234H: DSHSDSHU
THET293: DSHUDSSP`

**Comment by McIntireEvan** [comment]
Related: #33 

I remember hitting this error during Bitcamp last year. Would love to see it fixed. Maybe #34 could be a jumping-off point for writing the code for this.

It becomes tricky addressing the issue without changing the forward-facing api / data format

**Comment by McIntireEvan** [comment]
See https://github.com/umdio/umdio/blob/master/app/scrapers/courses_scraper.rb#L157 for the relevant code that causes this

**Comment by nyaculak** [comment]
@McIntireEvan Yeah, this would be tricky to fix without having to bump the major version for the API. Maybe we could add another field to the course object to specify a secondary+ gened list?

**Comment by McIntireEvan** [comment]
I think adding a secondary gened field is probably the cleanest solution we could hope for, right now. As a short term solution, I think it works well, and we can try and figure out a more long-term design (if needed) afterwards.
