### ISSUE TITLE
Restrictions field for courses

### ISSUE THREAD

**Issue by IsabellaS09** [umdio/umdio#6]
It looks like the restriction is being added twice.

**Comment by rrcobb** [comment]
Not sure I'm seeing this one. There are two similar-looking fields, 'restrictions' and 'restricted_to' - these are separate on Testudo, so we wanted to maintain the distinction in our database. 

Any more details on something being added twice?

**Comment by IsabellaS09** [comment]
If you look at the JSON for ENEE200 in the restriction field the same statement is there twice.

**Comment by rrcobb** [comment]
Oh hey! Looks like they are getting double added for lots of courses, http://api.umd.io/v0/courses/enee200,enee205,ence446 shows that. I think we've got a number of scraper fixes to make, this one will get made with them.
