### ISSUE TITLE
Inaccurate data

### ISSUE THREAD

**Issue by McIntireEvan** [umdio/umdio#64]
Some of the data from past semesters is flat out wront - i.e., compare [this](https://app.testudo.umd.edu/soc/search?courseId=cmsc131&sectionId=&termId=201708&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on) with [this](https://api.umd.io/v0/courses/sections?semester=201708&course=CMSC131). There's a clear discrepency here - also see https://api.umd.io/v0/courses/sections?semester=201705&course=CMSC131 

There are probably more examples, but this is the state of things right now. I'd be willing to bet it's due to building of various errors and such from the scraper over time, see #63 for some comments on that.

When we deploy the beta endpoint (soon), hopefully the data there will be correct

**Comment by vcapra1** [comment]
Still having issues with incorrect data: try https://api.umd.io/v0/courses/sections/aasp100-0101, and then compare it to the source at https://app.testudo.umd.edu/soc/201808/sections?courseIds=AASP100.  Completely wrong, says there are only 3 seats, and that there are "013" on the waitlist, when there are actually 0 on the waitlist and 13 in the holdfile.

Also, https://api.umd.io/v0/courses/sections/cmsc132-0101 doesn't show the number of open seats.

https://api.umd.io/v0/courses/sections/cmsc216-0101 shows incorrect number of total seats.

There are probably (definitely) more examples, but these are just a few I came across.  So it's not just past semesters.

**Comment by McIntireEvan** [comment]
Thanks for following up here and showing it's still an issue - I think if you try the beta api (https://bapi.umd.io/) for all of these, things should be working properly.

The two big steps I'll take to fix this are 
1. Improved way to re-scrape open seats, so we can call that in a cron job
2. Switch fully to docker in prod, so we can actually run things

**Comment by McIntireEvan** [comment]
All the remaining issues for this are resolved in #110
