### ISSUE TITLE
Courses without description blocks missing?

### ISSUE THREAD

**Issue by IsabellaS09** [umdio/umdio#8]
Courses like PHIL209E cannot be found by the API.

**Comment by rrcobb** [comment]
I'm not sure the course is happening next fall, the current semester on the api. The course turns up when we include the ongoing semester (Spring 2015) as the semester parameter. http://api.umd.io/v0/courses/PHIL209E?semester=201501 

This raises the important design question of specifying which semester we are returning - matching the testudo soc default semester seems like the right decision, but it gets confusing if the semester that's happening now is not the one that we're returning, eg. right now.

I'm gonna close this one, but reopen if I'm wrong about it.

**Comment by IsabellaS09** [comment]
Oh yeah, you're right. I must have had an extra search field that skewed my
results, sorry about that.
