### ISSUE TITLE
QoL: Only way to see all semesters is to input a bad semester

### ISSUE THREAD

**Issue by chen-justin** [umdio/umdio#88]
As far as I know the only way to show all semesters is to input a request like 
`http://api.umd.io/v0/courses?semester=012345`

TODO: Make a better way to access these at some point

**Comment by McIntireEvan** [comment]
Actually, we have https://api.umd.io/v0/courses/semesters, but seeing as it is not ordered in any meaningful way, and is not documented, it's not super useful right now

**Comment by McIntireEvan** [comment]
This is now in the docs, and is sorted, so closing
