### ISSUE TITLE
Whitespace issue

### ISSUE THREAD

**Issue by nickaversano** [umdio/umdio#9]
Course section AOSC652-AM01 instructors has weird whitespace issues. Instead of two instructors, the course returns a single instructor.

See http://api.umd.io/v0/courses/AOSC652/sections

**Comment by rrcobb** [comment]
We should be sanitizing fields as we scrape - not sure we did for that one. Almost makes me wish we were keeping track of testudo pages as a link for easier debugging. The html has a bunch of weird whitespace. https://ntst.umd.edu/soc/201508/sections?courseIds=AOSC652
